ITEM_ID_MAP = {}
ITEM_NAME_MAP = {}

--TODO: will be filled with apropriate vdf
ITEM_ID_MAP[1] = "ITMW_1H_FERROSSWORD_MIS"
ITEM_NAME_MAP["ITMW_1H_FERROSSWORD_MIS"] = "Feros Schwert"


ITEM_ID_MAP[1000] = "ITAR_SLD_H"
ITEM_NAME_MAP["ITAR_SLD_H"] = "Soeldnerruestung"

ITEM_ID_MAP[1001] = "ITAR_DJG_L"
ITEM_NAME_MAP["ITAR_DJG_L"] = "Drachenjaegerruestung"




ITEM_ID_MAP[2000] = "ITFO_APPLE"
ITEM_NAME_MAP["ITFO_APPLE"] = "Apfel"

ITEM_ID_MAP[2001] = "ITFOMUTTON"
ITEM_NAME_MAP["ITFOMUTTON"] = "Fleisch"

ITEM_ID_MAP[2002] = "ITFO_BREAD"
ITEM_NAME_MAP["ITFO_BREAD"] = "Brot"


ITEM_ID_MAP[2003] = "ITFO_FISH"
ITEM_NAME_MAP["ITFO_FISH"] = "Fisch"

ITEM_ID_MAP[2004] = "ITFO_CHEESE"
ITEM_NAME_MAP["ITFO_CHEESE"] = "Kaese"

ITEM_ID_MAP[2005] = "ITFO_BACON"
ITEM_NAME_MAP["ITFO_BACON"] = "Schinken"

ITEM_ID_MAP[2006] = "ITFO_SAUSAGE"
ITEM_NAME_MAP["ITFO_SAUSAGE"] = "Wurst"

ITEM_ID_MAP[2007] = "ITFO_HONEY"
ITEM_NAME_MAP["ITFO_HONEY"] = "Honig"


ITEM_ID_MAP[2008] = "ITFO_WATER"
ITEM_NAME_MAP["ITFO_WATER"] = "Wasser"

ITEM_ID_MAP[2009] = "ITFO_BEER"
ITEM_NAME_MAP["ITFO_BEER"]= "Bier"

ITEM_ID_MAP[2010] = "ITFO_BOOZE"
ITEM_NAME_MAP["ITFO_BOOZE"]= "Schnaps"

ITEM_ID_MAP[2011] = "ITFO_WINE"
ITEM_NAME_MAP["ITFO_WINE"]= "Wein"

ITEM_ID_MAP[2012] = "ITFO_MILK"
ITEM_NAME_MAP["ITFO_MILK"]= "Milch"

ITEM_ID_MAP[2013] = "ITFO_STEW"
ITEM_NAME_MAP["ITFO_STEW"]= "Fleischeintopf"

ITEM_ID_MAP[2014] = "ITFO_STEW"
ITEM_NAME_MAP["ITFO_STEW"]= "Kraeutereintopf"

ITEM_ID_MAP[2015] = "ITFO_FISHSOUP"
ITEM_NAME_MAP["ITFO_FISHSOUP"]= "Fischeintopf"



ITEM_ID_MAP[3000] = "ITPL_HEALTH_HERB_01"
ITEM_NAME_MAP["ITPL_HEALTH_HERB_01"] = "Heilpflanze"

ITEM_ID_MAP[3001] = "ITPL_HEALTH_HERB_03"
ITEM_NAME_MAP["ITPL_HEALTH_HERB_03"] = "Heilwurzel"


ITEM_ID_MAP[3002] = "ITPL_MANA_HERB_01"
ITEM_NAME_MAP["ITPL_MANA_HERB_01"] = "Feuernessel"

ITEM_ID_MAP[3003] = "ITPL_MANA_HERB_03"
ITEM_NAME_MAP["ITPL_MANA_HERB_03"] = "Feuerwurzel"

ITEM_ID_MAP[4000] = "ITPO_HEALTH_ADDON_04"
ITEM_NAME_MAP["ITPO_HEALTH_ADDON_04"] = "Reine Lebensenergie"

ITEM_ID_MAP[4001] = "ITPO_MANA_ADDON_04"
ITEM_NAME_MAP["ITPO_MANA_ADDON_04"] = "Reines Mana"

-- ab hier kommen customized tränke

ITEM_ID_MAP[4002] = "ITPO_MANA_01"
ITEM_NAME_MAP["ITPO_MANA_01"] = "Unbekannter Trank"

ITEM_ID_MAP[4003] = "ItPo_Mana_02"
ITEM_NAME_MAP["ItPo_Mana_02"] = "Unbekannter Trank"


ITEM_ID_MAP[4004] = "ItPo_Mana_03"
ITEM_NAME_MAP["ItPo_Mana_03"] = "Unbekannter Trank"


ITEM_ID_MAP[4005] = "ITPO_MANA_01"
ITEM_NAME_MAP["ITPO_MANA_01"] = "Unbekannter Trank"

ITEM_ID_MAP[5000] = "ITMW_2H_AXE_L_01"
ITEM_NAME_MAP["ITMW_2H_AXE_L_01"] = "Spitzhacke"


ITEM_ID_MAP[5001] = "ITLSTORCH"
ITEM_NAME_MAP["ITLSTORCH"] = "Fackel"


ITEM_ID_MAP[5002] = "ITMI_FLASK"
ITEM_NAME_MAP["ITMI_FLASK"] = "Laborwasserflasche"

ITEM_ID_MAP[5003] = "ITMI_SCOOP"
ITEM_NAME_MAP["ITMI_SCOOP"] = "Kochloeffel"