ITEM_ID_MAP = {}
ITEM_NAME_MAP = {}

--TODO: will be filled with apropriate vdf
ITEM_ID_MAP[1] = "ITMW_1H_FERROSSWORD_MIS"
ITEM_NAME_MAP["ITMW_1H_FERROSSWORD_MIS"] = "Feros Schwert"


ITEM_ID_MAP[3000] = "ITPL_HEALTH_HERB_01"
ITEM_NAME_MAP["ITPL_HEALTH_HERB_01"] = "Heilpflanze"

ITEM_ID_MAP[3001] = "ITPL_HEALTH_HERB_03"
ITEM_NAME_MAP["ITPL_HEALTH_HERB_03"] = "Heilwurzel"


ITEM_ID_MAP[3002] = "ITPL_MANA_HERB_01"
ITEM_NAME_MAP["ITPL_MANA_HERB_01"] = "Feuernessel"

ITEM_ID_MAP[3003] = "ITPL_MANA_HERB_03"
ITEM_NAME_MAP["ITPL_MANA_HERB_03"] = "Feuerwurzel"





