PRICE_TABLE = {}
PRICE_TABLE["ITNM_LANGSCHWERTEDEL"] = 1000
PRICE_TABLE["ITNM_KRIEGSSCHWERT"] = 500
PRICE_TABLE["ITNM_PRIESTKLINGE"] = 500
PRICE_TABLE["ITNM_BERSERKERWORT"] = 1000
PRICE_TABLE["ITNM_JAEGERAXT"] = 500
PRICE_TABLE["ITNM_RAEUBERAXT"] = 1000
PRICE_TABLE["ITNM_STREITKOLBEN"] = 500
PRICE_TABLE["ITNM_BERSERKERAXT"] = 1000
PRICE_TABLE["ITNM_BERSERKERSCHWERT"] = 1000


PRICE_TABLE["ITNM_PANZERMANTEL1"] = 2500
PRICE_TABLE["ITNM_PANZERMANTEL2"] = 2500
PRICE_TABLE["ITNM_KOENIGSRUESTUNG"] = 5000
PRICE_TABLE["ITNM_GOLDRUESTUNG"] = 5000
PRICE_TABLE["ITNM_LANDSKNECHTRUESTUNG"] = 1000
PRICE_TABLE["ITNM_KRIEGERINRUESTUNG"] = 1000
PRICE_TABLE["ITNM_ROTETUNIKA"] = 1000
PRICE_TABLE["ITNM_KOPFGELDJAEGERRUESTUNG"] = 1000

PRICE_TABLE["ITAR_SLD_H"] = 2500
PRICE_TABLE["ITAR_DJG_L"] = 2500


PRICE_TABLE["ITMW_2H_AXE_L_01"] = 100
PRICE_TABLE["ITRW_ARROW"] = 5

PRICE_TABLE["ITMI_GOLDNUGGET_ADDON"] = 18
PRICE_TABLE["ITAT_WARGFUR"] = 25
PRICE_TABLE["ITAT_SHADOWFUR"] = 250
PRICE_TABLE["ITAT_TROLLFUR"] = 300
PRICE_TABLE["ITAT_WOLFFUR"] = 10
PRICE_TABLE["ITAT_ADDON_KEILERFUR"] = 15


PRICE_TABLE["ITFO_WATER"] = 5
PRICE_TABLE["ITFO_BEER"] = 10
PRICE_TABLE["ITFO_BOOZE"] = 15


